### PR TITLE
Allow custom chains to be present

### PR DESCRIPTION
**Pull request by mnederlof**
Other than the default chains like INPUT, FORWARD, OUTPUT

### CODE REVIEW

**Comment by cloudlab-autobuild** [comment]
Can one of the admins verify this patch?

**Comment by fpytloun** [comment]
Failing test on syntax:
https://travis-ci.org/salt-formulas/salt-formula-iptables/jobs/243699857

**Comment by mnederlof** [comment]
no clue on how to fix latest failed build, in production i can just repeat the process a second time, and then it works...

**Comment by mnederlof** [comment]
@fpytloun can you help me figure out why the checks are failing right now? (because i think they are correct)

**Comment by fpytloun** [comment]
You need to wrap your changes with condition on LXC or Docker to skip these actions. Because they are not able to run iptables.

```
{%- if grains.get('virtual_subtype', None) not in ['Docker', 'LXC'] %}
```

**Comment by mnederlof** [comment]
Can one of the admins verify this patch?

**Pull request merged**
